version: '3'

services:
  grpc_server:
    container_name: todolist-grpc-server
    build:
      context: .
      dockerfile: ./docker/grpc.dockerfile
    ports:
      - 50051:50051
    tty:
      true
    volumes:
      - .:/grpc
    depends_on:
      - database

  web:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    ports:
      - 8080:8080
    tty:
      true
    volumes:
      - .:/todolist
    depends_on:
      - grpc_server
    container_name: todolist-docker-web
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    container_name: todolist-docker-db
    build:
      context: .
      dockerfile: ./docker/database.dockerfile
    networks:
      - default
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: todolist
    container_name: todolist-docker-db
    volumes:
      - todolist-docker-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  todolist-docker-data:

